namespaces:
  - id: 0
    name: Photo
  - id: 1
    name: Event

dsn: postgres://postgres:dev_pass@postgres:5432/keto

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467
